name: 'Porter CLI Installer'
description: 'Install the Porter CLI from a private repository release'
inputs:
  token:
    description: 'GitHub Personal Access Token with access to the private repository'
    required: true
  version:
    description: 'Tag of the Porter CLI release to install (can be any valid tag format)'
    required: false
    default: 'latest'


branding:
  color: 'blue'
  icon: 'download'

runs:
  using: 'composite'
  steps:
    - name: Download Porter CLI from private release
      shell: bash
      run: |
        echo "Downloading Porter CLI ${{ inputs.version }} from porter-dev/code"
        
        # Create a temporary directory for download
        TEMP_DIR=$(mktemp -d)
        
        # Get the release ID associated with the tag
        RELEASE_ID=$(curl -s -H "Authorization: token ${{ inputs.token }}" \
          "https://api.github.com/repos/porter-dev/code/releases/tags/${{ inputs.version }}" | \
          jq -r '.id')
        
        # Download the binary directly by tag and filename
        curl -L \
          -H "Authorization: token ${{ inputs.token }}" \
          -H "Accept: application/octet-stream" \
          --output "$TEMP_DIR/porter" \
          "https://api.github.com/repos/porter-dev/code/releases/$RELEASE_ID/assets?name=porter" | \
          jq -r '.[0].browser_download_url' | \
          xargs curl -L -H "Authorization: token ${{ inputs.token }}" \
          -H "Accept: application/octet-stream" \
          --output "$TEMP_DIR/porter"
        
        # Make the binary executable
        chmod +x "$TEMP_DIR/porter"
        
        # Make Porter CLI available in PATH
        mkdir -p $GITHUB_WORKSPACE/bin
        mv "$TEMP_DIR/porter" $GITHUB_WORKSPACE/bin/
        echo "$GITHUB_WORKSPACE/bin" >> $GITHUB_PATH
        
        # Clean up
        rm -rf "$TEMP_DIR"
        
        # Verify installation
        echo "Porter CLI installed successfully"
