name: 'Porter CLI Builder'
description: 'Checkout and build the Porter CLI from the legacy backend repository'
inputs:
  private_branch:
    description: 'The branch to checkout from the private repository'
    required: true
  token:
    description: 'GitHub Personal Access Token with access to the private repository'
    required: true

branding:
  color: 'blue'
  icon: 'lock'

runs:
  using: 'composite'
  steps:
    - name: Checkout private repository
      uses: actions/checkout@v3
      with:
        repository: porter-dev/code
        ref: ${{ inputs.private_branch }}
        token: ${{ inputs.token }}
        path: code
      
    - name: Build Porter CLI
      shell: bash
      working-directory: code/legacy-backend
      run: |
        echo "Building Porter CLI from branch ${{ inputs.private_branch }}"
        # Ensure we have the dependencies
        go mod download
        # Build the CLI
        go build -o porter ./cli/main.go
        
    - name: Make Porter CLI available in PATH
      shell: bash
      run: |
        echo "Making Porter CLI available in PATH"
        mkdir -p $GITHUB_WORKSPACE/bin
        cp code/legacy-backend/porter $GITHUB_WORKSPACE/bin/
        echo "$GITHUB_WORKSPACE/bin" >> $GITHUB_PATH
        chmod +x $GITHUB_WORKSPACE/bin/porter
