name: 'Porter CLI Installer'
description: 'Install the Porter CLI from a private repository release'
inputs:
  token:
    description: 'GitHub Personal Access Token with access to the private repository'
    required: true
  version:
    description: 'Tag of the Porter CLI release to install (can be any valid tag format)'
    required: false
    default: 'latest'

branding:
  color: 'blue'
  icon: 'download'

runs:
  using: 'composite'
  steps:
    - name: Download Porter CLI from private release
      shell: bash
      run: |
        echo "Downloading Porter CLI ${{ inputs.version }} from porter-dev/code"
        
        # Create a temporary directory for download
        TEMP_DIR=$(mktemp -d)
        
        # First get the release information by tag
        RELEASE_INFO=$(curl -sL -H "Authorization: token ${{ inputs.token }}" \
          "https://api.github.com/repos/porter-dev/code/releases/tags/${{ inputs.version }}")
        
        # Get the asset ID for the porter binary
        ASSET_ID=$(echo "$RELEASE_INFO" | jq -r '.assets[] | select(.name == "porter") | .id')
        
        if [ -z "$ASSET_ID" ] || [ "$ASSET_ID" = "null" ]; then
          echo "Error: Could not find porter binary in release with tag ${{ inputs.version }}"
          exit 1
        fi
        
        # Download the binary directly using the asset ID
        curl -sL \
          -H "Authorization: token ${{ inputs.token }}" \
          -H "Accept: application/octet-stream" \
          --output "$TEMP_DIR/porter" \
          "https://api.github.com/repos/porter-dev/code/releases/assets/$ASSET_ID"
        
        # Make the binary executable
        chmod +x "$TEMP_DIR/porter"
        
        # Make Porter CLI available in PATH
        mkdir -p $GITHUB_WORKSPACE/bin
        mv "$TEMP_DIR/porter" $GITHUB_WORKSPACE/bin/
        echo "$GITHUB_WORKSPACE/bin" >> $GITHUB_PATH
        
        # Clean up
        rm -rf "$TEMP_DIR"
        
        echo "Porter CLI installed successfully"
